export type RoutineExerciseSeed = {
  muscleGroup: string;
  exercise: string;
};

export const EXERCISE_CATALOG_SOURCES = [
  "https://www.acefitness.org/resources/pros/exercise-library/",
  "https://www.nasm.org/exercise-library",
  "https://www.healthline.com/health/fitness-exercise",
  "https://www.mayoclinic.org/healthy-lifestyle/fitness/in-depth/strength-training/art-20046670"
];

export const DEFAULT_EXERCISE_CATALOG: RoutineExerciseSeed[] = [
  { muscleGroup: "Pecho", exercise: "Press de banca con barra" },
  { muscleGroup: "Pecho", exercise: "Press inclinado con mancuernas" },
  { muscleGroup: "Pecho", exercise: "Press declinado con barra" },
  { muscleGroup: "Pecho", exercise: "Press en maquina convergente" },
  { muscleGroup: "Pecho", exercise: "Fondos en paralelas para pecho" },
  { muscleGroup: "Pecho", exercise: "Flexiones de pecho" },
  { muscleGroup: "Pecho", exercise: "Aperturas con mancuernas en banco plano" },
  { muscleGroup: "Pecho", exercise: "Aperturas en polea (crossover)" },
  { muscleGroup: "Pecho", exercise: "Pullover con mancuerna" },
  { muscleGroup: "Pecho", exercise: "Press con mancuernas agarre neutro" },

  { muscleGroup: "Espalda", exercise: "Dominadas pronas" },
  { muscleGroup: "Espalda", exercise: "Dominadas supinas" },
  { muscleGroup: "Espalda", exercise: "Jalon al pecho agarre ancho" },
  { muscleGroup: "Espalda", exercise: "Jalon al pecho agarre neutro" },
  { muscleGroup: "Espalda", exercise: "Remo con barra" },
  { muscleGroup: "Espalda", exercise: "Remo con mancuerna a una mano" },
  { muscleGroup: "Espalda", exercise: "Remo en polea baja" },
  { muscleGroup: "Espalda", exercise: "Remo en maquina pecho apoyado" },
  { muscleGroup: "Espalda", exercise: "Peso muerto convencional" },
  { muscleGroup: "Espalda", exercise: "Pullover en polea recta" },

  { muscleGroup: "Hombros", exercise: "Press militar con barra" },
  { muscleGroup: "Hombros", exercise: "Press militar sentado con mancuernas" },
  { muscleGroup: "Hombros", exercise: "Arnold press" },
  { muscleGroup: "Hombros", exercise: "Elevaciones laterales con mancuernas" },
  { muscleGroup: "Hombros", exercise: "Elevaciones laterales en polea" },
  { muscleGroup: "Hombros", exercise: "Pajaro con mancuernas" },
  { muscleGroup: "Hombros", exercise: "Face pull en polea" },
  { muscleGroup: "Hombros", exercise: "Remo al menton con barra EZ" },
  { muscleGroup: "Hombros", exercise: "Press en maquina de hombro" },
  { muscleGroup: "Hombros", exercise: "Elevaciones frontales con disco" },

  { muscleGroup: "Cuadriceps", exercise: "Sentadilla trasera alta" },
  { muscleGroup: "Cuadriceps", exercise: "Sentadilla frontal" },
  { muscleGroup: "Cuadriceps", exercise: "Hack squat" },
  { muscleGroup: "Cuadriceps", exercise: "Prensa de piernas inclinada" },
  { muscleGroup: "Cuadriceps", exercise: "Zancada caminando" },
  { muscleGroup: "Cuadriceps", exercise: "Split squat bulgaro" },
  { muscleGroup: "Cuadriceps", exercise: "Sentadilla goblet" },
  { muscleGroup: "Cuadriceps", exercise: "Step up con mancuernas" },
  { muscleGroup: "Cuadriceps", exercise: "Extension de cuadriceps en maquina" },
  { muscleGroup: "Cuadriceps", exercise: "Sissy squat asistida" },

  { muscleGroup: "Gluteos", exercise: "Hip thrust con barra" },
  { muscleGroup: "Gluteos", exercise: "Puente de gluteo con barra" },
  { muscleGroup: "Gluteos", exercise: "Sentadilla sumo con mancuerna" },
  { muscleGroup: "Gluteos", exercise: "Peso muerto sumo" },
  { muscleGroup: "Gluteos", exercise: "Patada de gluteo en polea" },
  { muscleGroup: "Gluteos", exercise: "Abduccion de cadera en maquina" },
  { muscleGroup: "Gluteos", exercise: "Pull through en polea" },
  { muscleGroup: "Gluteos", exercise: "Lunge inverso" },
  { muscleGroup: "Gluteos", exercise: "Frog pumps" },
  { muscleGroup: "Gluteos", exercise: "Kettlebell swing" },

  { muscleGroup: "Isquiosurales", exercise: "Peso muerto rumano con barra" },
  { muscleGroup: "Isquiosurales", exercise: "Peso muerto rumano con mancuernas" },
  { muscleGroup: "Isquiosurales", exercise: "Buenos dias con barra" },
  { muscleGroup: "Isquiosurales", exercise: "Curl femoral tumbado" },
  { muscleGroup: "Isquiosurales", exercise: "Curl femoral sentado" },
  { muscleGroup: "Isquiosurales", exercise: "Nordic ham curl" },
  { muscleGroup: "Isquiosurales", exercise: "Curl femoral unilateral" },
  { muscleGroup: "Isquiosurales", exercise: "Glute ham raise" },
  { muscleGroup: "Isquiosurales", exercise: "Peso muerto rumano a una pierna" },
  { muscleGroup: "Isquiosurales", exercise: "Curl femoral en polea baja" },

  { muscleGroup: "Biceps", exercise: "Curl con barra recta" },
  { muscleGroup: "Biceps", exercise: "Curl con barra EZ" },
  { muscleGroup: "Biceps", exercise: "Curl alterno con mancuernas" },
  { muscleGroup: "Biceps", exercise: "Curl martillo" },
  { muscleGroup: "Biceps", exercise: "Curl inclinado con mancuernas" },
  { muscleGroup: "Biceps", exercise: "Curl en banco predicador" },
  { muscleGroup: "Biceps", exercise: "Curl concentrado" },
  { muscleGroup: "Biceps", exercise: "Curl en polea baja con barra" },
  { muscleGroup: "Biceps", exercise: "Curl spider" },
  { muscleGroup: "Biceps", exercise: "Curl inverso con barra" },

  { muscleGroup: "Triceps", exercise: "Press frances con barra EZ" },
  { muscleGroup: "Triceps", exercise: "Extension por encima de la cabeza con mancuerna" },
  { muscleGroup: "Triceps", exercise: "Fondos en paralelas para triceps" },
  { muscleGroup: "Triceps", exercise: "Jalon de triceps en polea alta" },
  { muscleGroup: "Triceps", exercise: "Jalon de triceps con cuerda" },
  { muscleGroup: "Triceps", exercise: "Patada de triceps con mancuerna" },
  { muscleGroup: "Triceps", exercise: "Press de banca con agarre cerrado" },
  { muscleGroup: "Triceps", exercise: "Rompecraneos con barra EZ" },
  { muscleGroup: "Triceps", exercise: "Extension unilateral de triceps en polea" },
  { muscleGroup: "Triceps", exercise: "Press en maquina de fondos" },

  { muscleGroup: "Core", exercise: "Plancha frontal" },
  { muscleGroup: "Core", exercise: "Plancha lateral" },
  { muscleGroup: "Core", exercise: "Crunch en suelo" },
  { muscleGroup: "Core", exercise: "Crunch en polea alta" },
  { muscleGroup: "Core", exercise: "Elevaciones de piernas colgado" },
  { muscleGroup: "Core", exercise: "Rueda abdominal" },
  { muscleGroup: "Core", exercise: "Dead bug" },
  { muscleGroup: "Core", exercise: "Pallof press" },
  { muscleGroup: "Core", exercise: "Russian twist con disco" },
  { muscleGroup: "Core", exercise: "Hollow body hold" },

  { muscleGroup: "Gemelos y agarre", exercise: "Elevacion de talones de pie" },
  { muscleGroup: "Gemelos y agarre", exercise: "Elevacion de talones sentado" },
  { muscleGroup: "Gemelos y agarre", exercise: "Elevacion de talones en prensa" },
  { muscleGroup: "Gemelos y agarre", exercise: "Paseo del granjero" },
  { muscleGroup: "Gemelos y agarre", exercise: "Encogimiento de muneca supino" },
  { muscleGroup: "Gemelos y agarre", exercise: "Encogimiento de muneca prono" },
  { muscleGroup: "Gemelos y agarre", exercise: "Curl inverso con barra EZ" },
  { muscleGroup: "Gemelos y agarre", exercise: "Pinch grip con discos" },
  { muscleGroup: "Gemelos y agarre", exercise: "Colgado pasivo en barra" },
  { muscleGroup: "Gemelos y agarre", exercise: "Pronacion y supinacion con mancuerna" }
];

